### ISSUE TITLE
Create helper for mapping selectors

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-redux-utils#1]
```js
import { selectors } from '../reducer'

const mapStateToProps = mapSelectors([
  'propOne',
  'propTwo',
  ...
], selectors)
```

**Comment by dpikt** [comment]
¯\\\_(ツ)\_/¯

**Comment by dpikt** [comment]
Back from the dead! Some alternate syntax for you to ponder @chawes13.

```
import { selectors } from '../reducer'

...
 
function mapStateToProps (state) {
    return {
        ...mapSelectors(selectors, state),
       otherThing: userSelectors.user(state),
    }
}

compose(
   connect(mapStateToProps)
)(Component)
```

```
import { selectors } from '../reducer'

compose(
   connect(mapSelectors(selectors))
)(Component)
```

```
import { selectors } from '../reducer'


compose(
   withSelectors(selectors)
)(Component)
```

**Comment by chawes13** [comment]
Can you remind me of the context of this issue? What's the benefit?

**Comment by dpikt** [comment]
Removing an extra step of adding selectors to `mapStateToProps` once defining them. Small potatoes, just an interesting idea.

**Comment by chawes13** [comment]
Hm, wouldn't this obfuscate the prop names to use in lifecycle methods and the render function?

**Comment by dpikt** [comment]
Yeah, the idea would be each view has access to everything in its reducer slice. So you would look there to know the props (or react devtools).

**Comment by dpikt** [comment]
Related idea- spreading in actions:
```
import * as apiActions from 'api-actions'
import * as actions from '../actions'

const mapDispatchToProps = {
   ...apiActions,
   ...actions,
}
```

**Comment by chawes13** [comment]
Is this a pain point that you have? Personally I think this makes context switching harder by having to leave the view(s) to look at the reducer. Especially from a code review / indirectly involved developer standpoint

**Comment by dpikt** [comment]
Not really tbh. Out of all of these options I think spreading in api-actions is the most appealing. But that too would obscure some props.

The greater context is that I'm brainstorming ways to reduce the time it takes to load data into a view, so any ideas you have along those lines would be welcome!

**Comment by dpikt** [comment]
Haven't needed it.
